spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_resources?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 1000MB
  web:
    resources:
      static-locations: classpath:/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.kaede.myResources.pojo

